services:
  noteservice:
    build:
      context: ./NoteService
    container_name: noteservice
    networks:
      - noteservice_net
    ports:
      - "8080:8080"
    depends_on:
      psql:
        condition: service_healthy
  psql:
    image: postgres:16
    container_name: notesstorage
    ports:
      - "5432:5432"
    networks:
      - noteservice_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: notes_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
    - noteservice_psql_volume:/var/lib/postgresql/data

  # добавить прометей
  # добавить графану

networks:
  noteservice_net:

volumes:
  noteservice_psql_volume: